name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: mvn spring-boot:build-image

      - name: Deploy to server
        run: |
          ssh user@your-server-ip "docker stop your-container-name || true"
          ssh user@your-server-ip "docker rm your-container-name || true"
          ssh user@your-server-ip "docker pull your-image-name"
          ssh user@your-server-ip "docker run -d --name your-container-name -p 8080:8080 your-image-name"
